CREATE PROCEDURE MUSTERIHAREKETLER
AS
SELECT HAREKETID AS 'KIMLIK', URUNAD AS 'URUN ADI', TBLMUSTERIHAREKETLER.ADET, (TBLPERSONELLER.AD+' '+TBLPERSONELLER.SOYAD) AS 'PERSONEL',
(TBLMUSTERILER.AD+' '+TBLMUSTERILER.SOYAD) AS 'MUSTERI', FIYAT,TOPLAM,(TBLFATURABILGI.SERI+' '+TBLFATURABILGI.SIRANO) AS 'FATURA',
TBLMUSTERIHAREKETLER.TARIH,NOTLAR

FROM TBLMUSTERIHAREKETLER

inner join TBLURUNLER
ON
TBLMUSTERIHAREKETLER.URUNID=TBLURUNLER.ID

inner join TBLPERSONELLER
ON
TBLMUSTERIHAREKETLER.PERSONEL=TBLPERSONELLER.ID

inner join TBLMUSTERILER
ON
TBLMUSTERIHAREKETLER.MUSTERI=TBLMUSTERILER.ID

inner join TBLFATURABILGI
ON
TBLMUSTERIHAREKETLER.FATURAID=TBLFATURABILGI.FATURABILGIID